version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bobs_corn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_container
    restart: always
    environment:
      PORT: 8080
      DB_HOST: postgres_container
      DB_PORT: 5432
      DB_USER: bob
      DB_PASSWORD: password
      DB_NAME: bobs_corn
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data:
